# Предварительная сборка

FROM golang:1.23.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Собираем статически слинкованный бинарник для Alpine
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o marketplace ./cmd/api

# Минимальный образ для запуска приложения
FROM alpine:3.21.3

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata && \
    addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder --chown=appuser:appgroup /app/marketplace .

COPY --from=builder --chown=appuser:appgroup /app/migrations ./migrations

# Настройки времени и прав
RUN chmod +x marketplace

USER appuser

EXPOSE 8080

# HEALTHCHECK --interval=30s --timeout=3s \
#   CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

CMD ["./marketplace"]